import os
import sys

import psycopg2 as dbapi2


INIT_STATEMENTS = [
    """CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(40) NOT NULL,
	PASSWORD VARCHAR(300) NOT NULL,
	E_MAIL VARCHAR(80) NOT NULL,
	TYPE VARCHAR(20) NOT NULL
    );""",

    """CREATE TABLE RELATIONS (
	ID SERIAL PRIMARY KEY,
	CHILD_ID INTEGER NOT NULL,
	PARENT_ID INTEGER NOT NULL,
	FOREIGN KEY (CHILD_ID) REFERENCES USERS(ID)
	ON DELETE CASCADE,
	FOREIGN KEY (PARENT_ID) REFERENCES USERS(ID)
	ON DELETE CASCADE
    );""",
    """CREATE TABLE CUSTOMERS (
	USER_ID INTEGER PRIMARY KEY,
	FULL_NAME VARCHAR(50) NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
	ON DELETE CASCADE
    );""",
    """CREATE TABLE BRANCHES (
	USER_ID INTEGER PRIMARY KEY,
	FULL_NAME VARCHAR(50) NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
	ON DELETE CASCADE
    ); """,
    """CREATE TABLE HEADQUARTERS (
	USER_ID INTEGER PRIMARY KEY,
	FULL_NAME VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
    ON DELETE CASCADE
    );""",
    """CREATE TABLE PRICES (
	ID SERIAL PRIMARY KEY,
	HQ_ID INTEGER NOT NULL,
	BRANCH_ID INTEGER,
	OILED INTEGER NOT NULL,
	DARK INTEGER NOT NULL,
	LIGHT INTEGER NOT NULL,
	EDGED INTEGER NOT NULL,
	FOREIGN KEY (HQ_ID) REFERENCES HEADQUARTERS(USER_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(USER_ID)
	ON DELETE CASCADE
    );""",
    """CREATE TABLE DEPOSITS (
	ID SERIAL PRIMARY KEY,
	CUSTOMER_ID INTEGER NOT NULL,
	BRANCH_ID INTEGER NOT NULL,
	HQ_ID INTEGER NOT NULL,
	OILED_KG INTEGER,
	OILED_YIELD INTEGER,
	DARK_KG INTEGER,
	DARK_YIELD INTEGER,
	LIGHT_KG INTEGER,
	LIGHT_YIELD INTEGER,
	EDGED_KG INTEGER,
	EDGED_YIELD INTEGER,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(USER_ID)
    ON DELETE CASCADE,
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(USER_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (HQ_ID) REFERENCES HEADQUARTERS(USER_ID)
	ON DELETE CASCADE
    );""",
    """CREATE TABLE TRANSACTIONS (
	ID SERIAL PRIMARY KEY,
	DEPOSIT_ID INTEGER,
	DATE TIMESTAMP NOT NULL,
	PRICE INTEGER,
	OILED INTEGER,
	DARK INTEGER,
	LIGHT INTEGER,
	EDGED INTEGER,
	FOREIGN KEY (DEPOSIT_ID) REFERENCES DEPOSITS(ID)
 	ON DELETE CASCADE
    );""",
]


def initialize(url):
    with dbapi2.connect(url) as connection:
        cursor = connection.cursor()
        for statement in INIT_STATEMENTS:
            cursor.execute(statement)
        cursor.close()


if __name__ == "__main__":
    url = os.getenv("DATABASE_URL")
    if url is None:
        print("Usage: DATABASE_URL=url python dbinit.py", file=sys.stderr)
        sys.exit(1)
    initialize(url)
